# runtime: python37
# service: dots-crawler

# runtime_config:
#     python_version: 3

# handlers:
# - url: /.*
#   script: auto

runtime: custom
env: flex
service: dots-crawler
entrypoint: gunicorn -b :$PORT main:app --timeout 180

readiness_check:
  app_start_timeout_sec: 1800