FROM gcr.io/google-appengine/python
RUN apt-get update
RUN apt-get install -y unzip
RUN apt-get install -y openjdk-8-jre

RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
RUN echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
RUN apt-get -y update
RUN apt-get -y install google-chrome-stable

# RUN wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
# RUN unzip chromedriver_linux64.zip
# RUN apt-get install -y chromium

LABEL python_version=python
RUN virtualenv --no-download /env -p python3.7
ENV VIRTUAL_ENV /env
ENV PATH /env/bin:$PATH
ADD requirements.txt /app/
RUN pip install -r requirements.txt
# RUN pip3 install newspaper3k
RUN python -m nltk.downloader punkt

ADD . /app/
CMD exec gunicorn -b :$PORT main:app --timeout 180